[FIX] shopinvader_api_cart: fix the empty cart creation upon update
Steps to reproduce:

- Perform an update without any existing cart

Exception:

```
TypeError: SaleOrder._create_empty_cart() missing 1 required positional
argument: 'partner_id'
```